//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4961
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4961.
// 
#pragma warning disable 1591

namespace RemoveUnids.CookWebSrv {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DominoSoapBinding", Namespace="urn:DefaultNamespace")]
    public partial class ListCustomers : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LISTCUSTOMERSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ListCustomers() {
            this.Url = global::RemoveUnids.Properties.Settings.Default.RemoveUnids_CookWebSrv_GetCustomersService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LISTCUSTOMERSCompletedEventHandler LISTCUSTOMERSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("LISTCUSTOMERSReturn", Namespace="urn:DefaultNamespace")]
        public string LISTCUSTOMERS([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:DefaultNamespace")] string DBNAME, [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:DefaultNamespace")] string VIEWNAME) {
            object[] results = this.Invoke("LISTCUSTOMERS", new object[] {
                        DBNAME,
                        VIEWNAME});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LISTCUSTOMERSAsync(string DBNAME, string VIEWNAME) {
            this.LISTCUSTOMERSAsync(DBNAME, VIEWNAME, null);
        }
        
        /// <remarks/>
        public void LISTCUSTOMERSAsync(string DBNAME, string VIEWNAME, object userState) {
            if ((this.LISTCUSTOMERSOperationCompleted == null)) {
                this.LISTCUSTOMERSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLISTCUSTOMERSOperationCompleted);
            }
            this.InvokeAsync("LISTCUSTOMERS", new object[] {
                        DBNAME,
                        VIEWNAME}, this.LISTCUSTOMERSOperationCompleted, userState);
        }
        
        private void OnLISTCUSTOMERSOperationCompleted(object arg) {
            if ((this.LISTCUSTOMERSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LISTCUSTOMERSCompleted(this, new LISTCUSTOMERSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void LISTCUSTOMERSCompletedEventHandler(object sender, LISTCUSTOMERSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LISTCUSTOMERSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LISTCUSTOMERSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591